FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run generate:client
RUN npm run build


EXPOSE 8080

CMD ["sh", "-c", "node dist/worker.js"]