// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
    GetTodosResponse,
    CreateTodoData,
    CreateTodoResponse,
    GetTodoData,
    GetTodoResponse,
    UpdateTodoData,
    UpdateTodoResponse,
    DeleteTodoData,
    DeleteTodoResponse,
    GetTodosByRelationshipData,
    GetTodosByRelationshipResponse,
    CreateTaskTypeData,
    CreateTaskTypeResponse,
    GetTaskTypesResponse,
    GetTaskTypeData,
    GetTaskTypeResponse,
    CreateSubTaskData,
    CreateSubTaskResponse,
    GetSubTasksResponse,
    GetSubTaskData,
    GetSubTaskResponse,
    GetSubTasksByTaskTypeData,
    GetSubTasksByTaskTypeResponse,
    CreateScheduleData,
    CreateScheduleResponse,
    GetSchedulesResponse,
    GetScheduleData,
    GetScheduleResponse,
    UpdateScheduleData,
    UpdateScheduleResponse,
    DeleteScheduleData,
    DeleteScheduleResponse,
    GetSchedulesForCaregiverData,
    GetSchedulesForCaregiverResponse,
    GetSchedulesForRecipientData,
    GetSchedulesForRecipientResponse,
    GetSchedulesForCaregiverAndRecipientData,
    GetSchedulesForCaregiverAndRecipientResponse,
    AddRecipientToCaregiverData,
    AddRecipientToCaregiverResponse,
    GetAllRelationshipsResponse,
    GetRelationshipsForRecipientData,
    GetRelationshipsForRecipientResponse,
    GetRelationshipsForCaregiverData,
    GetRelationshipsForCaregiverResponse,
    UpdateRelationshipData,
    UpdateRelationshipResponse,
    DeleteRelationshipData,
    DeleteRelationshipResponse,
    GetRecipientsResponse,
    CreateRecipientData,
    CreateRecipientResponse,
    GetRecipientData,
    GetRecipientResponse,
    UpdateRecipientData,
    UpdateRecipientResponse,
    DeleteRecipientData,
    DeleteRecipientResponse,
    UpdateRecipientPasswordData,
    UpdateRecipientPasswordResponse,
    LoginData,
    LoginResponse,
    CreateLogData,
    CreateLogResponse,
    GetLogsResponse,
    GetLogByIdData,
    GetLogByIdResponse,
    UpdateLogData,
    UpdateLogResponse,
    DeleteLogData,
    DeleteLogResponse,
    GetOpenLogsResponse,
    GetLogsForRelationshipData,
    GetLogsForRelationshipResponse,
    GetCaregiversResponse,
    CreateCaregiverData,
    CreateCaregiverResponse,
    GetCaregiverData,
    GetCaregiverResponse,
    UpdateCaregiverData,
    UpdateCaregiverResponse,
    DeleteCaregiverData,
    DeleteCaregiverResponse,
    UpdateCaregiverPasswordData,
    UpdateCaregiverPasswordResponse,
    GetAdminsResponse,
    CreateAdminData,
    CreateAdminResponse,
    GetAdminData,
    GetAdminResponse,
    UpdateAdminData,
    UpdateAdminResponse,
    DeleteAdminData,
    DeleteAdminResponse,
    UpdateAdminPasswordData,
    UpdateAdminPasswordResponse,
} from "./types.gen";

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getTodos = (): CancelablePromise<GetTodosResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/todos",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createTodo = (data: CreateTodoData): CancelablePromise<CreateTodoResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/todos",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getTodo = (data: GetTodoData): CancelablePromise<GetTodoResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/todos/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Todo not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateTodo = (data: UpdateTodoData): CancelablePromise<UpdateTodoResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/todos/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            404: "Todo not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteTodo = (data: DeleteTodoData): CancelablePromise<DeleteTodoResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/todos/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Todo not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.relationshipId
 * @returns unknown Ok
 * @throws ApiError
 */
export const getTodosByRelationship = (
    data: GetTodosByRelationshipData,
): CancelablePromise<GetTodosByRelationshipResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/todos/relationship/{relationshipId}",
        path: {
            relationshipId: data.relationshipId,
        },
        errors: {
            400: "Missing relationshipId",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createTaskType = (data: CreateTaskTypeData): CancelablePromise<CreateTaskTypeResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/task_types",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getTaskTypes = (): CancelablePromise<GetTaskTypesResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/task_types",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getTaskType = (data: GetTaskTypeData): CancelablePromise<GetTaskTypeResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/task_types/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Task type not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createSubTask = (data: CreateSubTaskData): CancelablePromise<CreateSubTaskResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/subtasks",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSubTasks = (): CancelablePromise<GetSubTasksResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/subtasks",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSubTask = (data: GetSubTaskData): CancelablePromise<GetSubTaskResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/subtasks/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Sub-task not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.taskTypeId
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSubTasksByTaskType = (
    data: GetSubTasksByTaskTypeData,
): CancelablePromise<GetSubTasksByTaskTypeResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/subtasks/task-type/{taskTypeId}",
        path: {
            taskTypeId: data.taskTypeId,
        },
        errors: {
            404: "No sub-tasks found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createSchedule = (data: CreateScheduleData): CancelablePromise<CreateScheduleResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/schedules",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSchedules = (): CancelablePromise<GetSchedulesResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSchedule = (data: GetScheduleData): CancelablePromise<GetScheduleResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Schedule not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateSchedule = (data: UpdateScheduleData): CancelablePromise<UpdateScheduleResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/schedules/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            404: "Schedule not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteSchedule = (data: DeleteScheduleData): CancelablePromise<DeleteScheduleResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/schedules/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Schedule not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.caregiverId
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSchedulesForCaregiver = (
    data: GetSchedulesForCaregiverData,
): CancelablePromise<GetSchedulesForCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/caregiver/{caregiverId}",
        path: {
            caregiverId: data.caregiverId,
        },
        errors: {
            404: "No schedules found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.recipientId
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSchedulesForRecipient = (
    data: GetSchedulesForRecipientData,
): CancelablePromise<GetSchedulesForRecipientResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/recipient/{recipientId}",
        path: {
            recipientId: data.recipientId,
        },
        errors: {
            404: "No schedules found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.caregiverId
 * @param data.recipientId
 * @returns unknown Ok
 * @throws ApiError
 */
export const getSchedulesForCaregiverAndRecipient = (
    data: GetSchedulesForCaregiverAndRecipientData,
): CancelablePromise<GetSchedulesForCaregiverAndRecipientResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/caregiver/{caregiverId}/recipient/{recipientId}",
        path: {
            caregiverId: data.caregiverId,
            recipientId: data.recipientId,
        },
        errors: {
            404: "No schedules found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const addRecipientToCaregiver = (
    data: AddRecipientToCaregiverData,
): CancelablePromise<AddRecipientToCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/relationships",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getAllRelationships = (): CancelablePromise<GetAllRelationshipsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/relationships",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getRelationshipsForRecipient = (
    data: GetRelationshipsForRecipientData,
): CancelablePromise<GetRelationshipsForRecipientResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/relationships/recipient/{id}/caregivers",
        path: {
            id: data.id,
        },
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getRelationshipsForCaregiver = (
    data: GetRelationshipsForCaregiverData,
): CancelablePromise<GetRelationshipsForCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/relationships/caregiver/{id}/recipients",
        path: {
            id: data.id,
        },
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateRelationship = (data: UpdateRelationshipData): CancelablePromise<UpdateRelationshipResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/relationships/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            404: "Relationship not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteRelationship = (data: DeleteRelationshipData): CancelablePromise<DeleteRelationshipResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/relationships/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Relationship not found",
            500: "Database error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getRecipients = (): CancelablePromise<GetRecipientsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/recipients",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createRecipient = (data: CreateRecipientData): CancelablePromise<CreateRecipientResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/recipients",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getRecipient = (data: GetRecipientData): CancelablePromise<GetRecipientResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/recipients/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Recipient not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateRecipient = (data: UpdateRecipientData): CancelablePromise<UpdateRecipientResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/recipients/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            404: "Recipient not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteRecipient = (data: DeleteRecipientData): CancelablePromise<DeleteRecipientResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/recipients/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Recipient not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateRecipientPassword = (
    data: UpdateRecipientPasswordData,
): CancelablePromise<UpdateRecipientPasswordResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/recipients/{id}/password",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields or invalid password",
            404: "Recipient not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const login = (data: LoginData): CancelablePromise<LoginResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/login",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            401: "Unauthorized",
            500: "Server error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createLog = (data: CreateLogData): CancelablePromise<CreateLogResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/logs",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            500: "Server Error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getLogs = (): CancelablePromise<GetLogsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs",
        errors: {
            500: "Server Error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getLogById = (data: GetLogByIdData): CancelablePromise<GetLogByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Log not found",
            500: "Server Error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateLog = (data: UpdateLogData): CancelablePromise<UpdateLogResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/logs/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            404: "Log not found",
            500: "Server Error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteLog = (data: DeleteLogData): CancelablePromise<DeleteLogResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/logs/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Log not found",
            500: "Server Error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getOpenLogs = (): CancelablePromise<GetOpenLogsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs/open",
        errors: {
            500: "Server Error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.recipientId
 * @param data.caregiverId
 * @returns unknown Ok
 * @throws ApiError
 */
export const getLogsForRelationship = (
    data: GetLogsForRelationshipData,
): CancelablePromise<GetLogsForRelationshipResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs/relationship/{recipientId}/{caregiverId}",
        path: {
            recipientId: data.recipientId,
            caregiverId: data.caregiverId,
        },
        errors: {
            404: "Relationship not found",
            500: "Server Error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getCaregivers = (): CancelablePromise<GetCaregiversResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/caregivers",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createCaregiver = (data: CreateCaregiverData): CancelablePromise<CreateCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/caregivers",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getCaregiver = (data: GetCaregiverData): CancelablePromise<GetCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/caregivers/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Caregiver not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateCaregiver = (data: UpdateCaregiverData): CancelablePromise<UpdateCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/caregivers/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            404: "Caregiver not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteCaregiver = (data: DeleteCaregiverData): CancelablePromise<DeleteCaregiverResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/caregivers/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Caregiver not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateCaregiverPassword = (
    data: UpdateCaregiverPasswordData,
): CancelablePromise<UpdateCaregiverPasswordResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/caregivers/{id}/password",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields or invalid password",
            404: "Caregiver not found",
            500: "Database error",
        },
    });
};

/**
 * @returns unknown Ok
 * @throws ApiError
 */
export const getAdmins = (): CancelablePromise<GetAdminsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/admins",
        errors: {
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const createAdmin = (data: CreateAdminData): CancelablePromise<CreateAdminResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/admins",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const getAdmin = (data: GetAdminData): CancelablePromise<GetAdminResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/admins/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Admin not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateAdmin = (data: UpdateAdminData): CancelablePromise<UpdateAdminResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/admins/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields",
            404: "Admin not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Ok
 * @throws ApiError
 */
export const deleteAdmin = (data: DeleteAdminData): CancelablePromise<DeleteAdminResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/admins/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Admin not found",
            500: "Database error",
        },
    });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Ok
 * @throws ApiError
 */
export const updateAdminPassword = (data: UpdateAdminPasswordData): CancelablePromise<UpdateAdminPasswordResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/admins/{id}/password",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing fields or invalid password",
            404: "Admin not found",
            500: "Database error",
        },
    });
};
