// This file is auto-generated by @hey-api/openapi-ts

export type PostLoginData = {
    requestBody: {
        email: string;
        password: string;
    };
};

export type PostLoginResponse = {
    message?: string;
    role?: string;
    token?: string;
    user?: {
        id?: number;
        name?: string;
        email?: string;
    };
};

export type PostLogsData = {
    requestBody: {
        id: string;
        date: string;
        relationshipId: string;
        finished: boolean;
        closed: boolean;
        tasks: Array<{
            subTaskId: string;
            startTime: string;
            endTime: string;
            done: boolean;
            note?: string;
        }>;
    };
};

export type PostLogsResponse = {
    message?: string;
    id?: string;
};

export type GetLogsResponse = Array<{
    id?: string;
    date?: string;
    relationshipId?: string;
    finished?: boolean;
    closed?: boolean;
    tasks?: Array<{
        subTaskId?: string;
        startTime?: string;
        endTime?: string;
        done?: boolean;
        note?: string;
    }>;
}>;

export type GetLogsByIdData = {
    id: string;
};

export type GetLogsByIdResponse = {
    id?: string;
    date?: string;
    relationshipId?: string;
    finished?: boolean;
    closed?: boolean;
    tasks?: Array<{
        subTaskId?: string;
        startTime?: string;
        endTime?: string;
        done?: boolean;
        note?: string;
    }>;
};

export type PutLogsByIdData = {
    id: string;
    requestBody: {
        id?: string;
        date?: string;
        relationshipId?: string;
        finished?: boolean;
        closed?: boolean;
        tasks?: Array<{
            subTaskId?: string;
            startTime?: string;
            endTime?: string;
            done?: boolean;
            note?: string;
        }>;
    };
};

export type PutLogsByIdResponse = unknown;

export type DeleteLogsByIdData = {
    id: string;
};

export type DeleteLogsByIdResponse = unknown;

export type GetLogsOpenResponse = Array<{
    id?: string;
    date?: string;
    relationshipId?: string;
    finished?: boolean;
    closed?: boolean;
    tasks?: Array<{
        subTaskId?: string;
        startTime?: string;
        endTime?: string;
        done?: boolean;
        note?: string;
    }>;
}>;

export type GetLogsRelationshipByRecipientIdByCaregiverIdData = {
    /**
     * ID of the caregiver
     */
    caregiverId: string;
    /**
     * ID of the recipient
     */
    recipientId: string;
};

export type GetLogsRelationshipByRecipientIdByCaregiverIdResponse = Array<{
    id?: string;
    date?: string;
    relationshipId?: string;
    finished?: boolean;
    closed?: boolean;
    tasks?: Array<{
        subTaskId?: string;
        startTime?: string;
        endTime?: string;
        done?: boolean;
        note?: string;
    }>;
}>;

export type GetAdminsResponse = Array<{
    id?: number;
    name?: string;
    email?: string;
}>;

export type PostAdminsData = {
    requestBody: {
        name: string;
        email: string;
        password: string;
    };
};

export type PostAdminsResponse = {
    id?: number;
    name?: string;
    email?: string;
    password?: string;
};

export type GetAdminsByIdData = {
    /**
     * Admin ID
     */
    id: number;
};

export type GetAdminsByIdResponse = {
    id?: number;
    name?: string;
    email?: string;
    password?: string;
};

export type PutAdminsByIdData = {
    /**
     * Admin ID
     */
    id: number;
    requestBody: {
        name: string;
        email: string;
    };
};

export type PutAdminsByIdResponse = unknown;

export type DeleteAdminsByIdData = {
    /**
     * Admin ID
     */
    id: number;
};

export type DeleteAdminsByIdResponse = unknown;

export type PutAdminsByIdPasswordData = {
    /**
     * Admin ID
     */
    id: number;
    requestBody: {
        currentPassword: string;
        newPassword: string;
    };
};

export type PutAdminsByIdPasswordResponse = unknown;

export type GetCaregiversResponse = Array<{
    id?: number;
    name?: string;
    phone?: string;
    email?: string;
}>;

export type PostCaregiversData = {
    requestBody: {
        name: string;
        email: string;
        phone: string;
        password: string;
    };
};

export type PostCaregiversResponse = {
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    password?: string;
};

export type GetCaregiversByIdData = {
    /**
     * Caregiver ID
     */
    id: number;
};

export type GetCaregiversByIdResponse = {
    id?: number;
    name?: string;
    phone?: string;
    email?: string;
};

export type PutCaregiversByIdData = {
    /**
     * Caregiver ID
     */
    id: number;
    requestBody: {
        name: string;
        email: string;
        phone: string;
    };
};

export type PutCaregiversByIdResponse = {
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
};

export type DeleteCaregiversByIdData = {
    /**
     * Caregiver ID
     */
    id: number;
};

export type DeleteCaregiversByIdResponse = unknown;

export type PutCaregiversByIdPasswordData = {
    /**
     * Caregiver ID
     */
    id: number;
    requestBody: {
        currentPassword: string;
        newPassword: string;
    };
};

export type PutCaregiversByIdPasswordResponse = unknown;

export type GetRecipientsResponse = Array<{
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    four_hand_care_needed?: boolean;
    caregiver_note?: string;
}>;

export type PostRecipientsData = {
    requestBody: {
        name: string;
        email: string;
        phone: string;
        address: string;
        four_hand_care_needed?: boolean;
        caregiver_note?: string;
        password: string;
    };
};

export type PostRecipientsResponse = {
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    four_hand_care_needed?: boolean;
    caregiver_note?: string;
};

export type GetRecipientsByIdData = {
    /**
     * Recipient ID
     */
    id: number;
};

export type GetRecipientsByIdResponse = {
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    four_hand_care_needed?: boolean;
    caregiver_note?: string;
};

export type PutRecipientsByIdData = {
    /**
     * Recipient ID
     */
    id: number;
    requestBody: {
        name: string;
        email: string;
        phone: string;
        address: string;
        four_hand_care_needed?: boolean;
        caregiver_note?: string;
    };
};

export type PutRecipientsByIdResponse = unknown;

export type DeleteRecipientsByIdData = {
    /**
     * Recipient ID
     */
    id: number;
};

export type DeleteRecipientsByIdResponse = unknown;

export type PutRecipientsByIdPasswordData = {
    /**
     * Recipient ID
     */
    id: number;
    requestBody: {
        currentPassword: string;
        newPassword: string;
    };
};

export type PutRecipientsByIdPasswordResponse = unknown;

export type PostCaregiversRecipientsData = {
    requestBody: {
        recipientId: number;
        caregiverId: number;
    };
};

export type PostCaregiversRecipientsResponse = {
    relationship_id?: number;
    recipientId?: number;
    caregiverId?: number;
};

export type GetRecipientsByIdCaregiversData = {
    /**
     * Recipient ID
     */
    id: number;
};

export type GetRecipientsByIdCaregiversResponse = Array<{
    id?: number;
    name?: string;
    phone?: string;
    email?: string;
    relationship_id?: number;
}>;

export type GetCaregiversByIdRecipientsData = {
    /**
     * Caregiver ID
     */
    id: number;
};

export type GetCaregiversByIdRecipientsResponse = Array<{
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    relationship_id?: number;
}>;

export type DeleteRelationshipsByIdData = {
    /**
     * Relationship ID
     */
    id: number;
};

export type DeleteRelationshipsByIdResponse = unknown;

export type PutRelationshipsByIdData = {
    /**
     * Relationship ID
     */
    id: number;
    requestBody: {
        recipientId: number;
        caregiverId: number;
    };
};

export type PutRelationshipsByIdResponse = unknown;

export type GetRelationshipsResponse = Array<{
    relationship_id?: number;
    recipient_id?: number;
    recipient_name?: string;
    caregiver_id?: number;
    caregiver_name?: string;
}>;

export type PostSchedulesData = {
    requestBody: {
        relationship_id: number;
        date: string;
        start_time: string;
        end_time: string;
    };
};

export type PostSchedulesResponse = {
    id?: number;
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
};

export type GetSchedulesResponse = Array<{
    id?: number;
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
}>;

export type GetSchedulesByIdData = {
    /**
     * Schedule ID
     */
    id: number;
};

export type GetSchedulesByIdResponse = {
    id?: number;
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
};

export type PutSchedulesByIdData = {
    /**
     * Schedule ID
     */
    id: number;
    requestBody: {
        relationship_id: number;
        date: string;
        start_time: string;
        end_time: string;
    };
};

export type PutSchedulesByIdResponse = unknown;

export type DeleteSchedulesByIdData = {
    /**
     * Schedule ID
     */
    id: number;
};

export type DeleteSchedulesByIdResponse = unknown;

export type GetSchedulesCaregiverByCaregiverIdData = {
    /**
     * ID of the caregiver
     */
    caregiverId: number;
};

export type GetSchedulesCaregiverByCaregiverIdResponse = Array<{
    id?: number;
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
}>;

export type GetSchedulesRecipientByRecipientIdData = {
    /**
     * ID of the recipient
     */
    recipientId: number;
};

export type GetSchedulesRecipientByRecipientIdResponse = Array<{
    id?: number;
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
}>;

export type GetSchedulesByCaregiverIdByRecipientIdData = {
    /**
     * ID of the caregiver
     */
    caregiverId: number;
    /**
     * ID of the recipient
     */
    recipientId: number;
};

export type GetSchedulesByCaregiverIdByRecipientIdResponse = Array<{
    id?: number;
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
}>;

export type PostTasktypesData = {
    requestBody: {
        type: string;
    };
};

export type PostTasktypesResponse = {
    id?: number;
    type?: string;
};

export type GetTasktypesResponse = Array<{
    id?: number;
    type?: string;
}>;

export type GetTasktypesByIdData = {
    id: number;
};

export type GetTasktypesByIdResponse = {
    id?: number;
    type?: string;
};

export type PostSubtasksData = {
    requestBody: {
        title: string;
        taskTypeId: number;
    };
};

export type PostSubtasksResponse = {
    id?: number;
    title?: string;
    tasktypeId?: number;
};

export type GetSubtasksResponse = Array<{
    id?: number;
    title?: string;
    tasktypeId?: number;
}>;

export type GetSubtasksByIdData = {
    id: number;
};

export type GetSubtasksByIdResponse = {
    id?: number;
    title?: string;
    tasktypeId?: number;
};

export type GetSubtasksTasktypeByTaskTypeIdData = {
    taskTypeId: number;
};

export type GetSubtasksTasktypeByTaskTypeIdResponse = Array<{
    id?: number;
    title?: string;
    tasktypeId?: number;
}>;

export type GetTodosResponse = Array<{
    id?: number;
    subtaskId?: number;
    relationshipId?: number;
    sequenceNumber?: number;
    done?: boolean;
}>;

export type PostTodosData = {
    requestBody: {
        subtaskId: number;
        relationshipId: number;
        sequenceNumber: number;
        done?: boolean;
    };
};

export type PostTodosResponse = {
    id?: number;
    subtaskId?: number;
    relationshipId?: number;
    sequenceNumber?: number;
    done?: boolean;
};

export type GetTodosByIdData = {
    id: number;
};

export type GetTodosByIdResponse = {
    id?: number;
    subtaskId?: number;
    relationshipId?: number;
    sequenceNumber?: number;
    done?: boolean;
};

export type PutTodosByIdData = {
    /**
     * Todo ID
     */
    id: number;
    requestBody: {
        subtaskId: number;
        relationshipId: number;
        sequenceNumber: number;
        done: boolean;
    };
};

export type PutTodosByIdResponse = unknown;

export type DeleteTodosByIdData = {
    /**
     * Todo ID
     */
    id: number;
};

export type DeleteTodosByIdResponse = unknown;

export type GetTodosRelationshipByRelationshipIdData = {
    relationshipId: number;
};

export type GetTodosRelationshipByRelationshipIdResponse = Array<{
    id?: number;
    subtaskId?: number;
    relationshipId?: number;
    sequenceNumber?: number;
    done?: boolean;
}>;
