// This file is auto-generated by @hey-api/openapi-ts

export type AdminWithoutPassword = {
    email: string;
    name: string;
    id: string;
};

export type CaregiverWithoutPassword = {
    id: string;
    name: string;
    email: string;
    phone: string;
};

export type CreateAdminRequest = {
    password: string;
    email: string;
    name: string;
};

export type CreateCaregiverRequest = {
    password: string;
    phone: string;
    email: string;
    name: string;
};

export type CreateOrUpdateTodoRequest = {
    subtaskId: string;
    relationshipId: string | null;
    sequenceNumber: number;
    done: boolean;
};

export type CreateRecipientRequest = {
    caregiverNote: string | null;
    fourHandCareNeeded: boolean;
    address: string;
    password: string;
    phone: string;
    email: string;
    name: string;
};

export type CreateSubTaskRequest = {
    title: string;
    taskTypeId: string;
};

export type CreateTaskTypeRequest = {
    type: string;
};

export type ErrorResponse = {
    error: string;
    message: string;
};

export type LogCreateResponse = {
    id: string;
};

export type LogEntry = {
    id: string;
    date: string;
    relationshipId: string;
    finished: boolean;
    closed: boolean;
    tasks: Array<TaskLog>;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginSuccessResponse = {
    role: "admin" | "caregiver";
    token: string;
    user: {
        email: string;
        name: string;
        id: string;
    };
};

export type role = "admin" | "caregiver";

export type RecipientCaregiverRelationship = {
    id: string;
    recipientId: string;
    caregiverId: string;
};

export type RecipientWithoutPassword = {
    id: string;
    name: string;
    email: string;
    phone: string;
    address: string;
    fourHandCareNeeded: boolean;
    caregiverNote: string | null;
};

export type RelationshipRequest = {
    recipientId: string;
    caregiverId: string;
};

export type Schedule = {
    id: string;
    date: string;
    relationshipId: string;
    startTime: string;
    endTime: string;
};

export type ScheduleRequest = {
    date: string;
    relationshipId: string;
    startTime: string;
    endTime: string;
};

export type Subtask = {
    id: string;
    title: string;
    taskTypeId: string | null;
};

export type SuccessResponse = {
    message: string;
};

export type TaskLog = {
    subTaskId: string;
    startTime: string;
    endTime: string;
    done: boolean;
    note?: string;
};

export type TaskType = {
    id: string;
    type: string;
};

export type Todo = {
    id: string;
    relationshipId: string | null;
    subtaskId: string;
    sequenceNumber: number;
    done: boolean;
};

export type UpdateAdminPasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type UpdateCaregiverPasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type UpdateLogEntry = {
    date: string;
    relationshipId: string;
    finished: boolean;
    closed: boolean;
    tasks: Array<TaskLog>;
};

export type UpdateRecipientPasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type GetTodosResponse = Array<Todo> | ErrorResponse;

export type CreateTodoData = {
    requestBody: CreateOrUpdateTodoRequest;
};

export type CreateTodoResponse = Todo | ErrorResponse;

export type GetTodoData = {
    id: string;
};

export type GetTodoResponse = Todo | ErrorResponse;

export type UpdateTodoData = {
    id: string;
    requestBody: CreateOrUpdateTodoRequest;
};

export type UpdateTodoResponse = SuccessResponse | ErrorResponse;

export type DeleteTodoData = {
    id: string;
};

export type DeleteTodoResponse = SuccessResponse | ErrorResponse;

export type GetTodosByRelationshipData = {
    relationshipId: string;
};

export type GetTodosByRelationshipResponse = Array<Todo> | ErrorResponse;

export type CreateTaskTypeData = {
    requestBody: CreateTaskTypeRequest;
};

export type CreateTaskTypeResponse = TaskType | ErrorResponse;

export type GetTaskTypesResponse = Array<TaskType> | ErrorResponse;

export type GetTaskTypeData = {
    id: string;
};

export type GetTaskTypeResponse = TaskType | ErrorResponse;

export type CreateSubTaskData = {
    requestBody: CreateSubTaskRequest;
};

export type CreateSubTaskResponse = Subtask | ErrorResponse;

export type GetSubTasksResponse = Array<Subtask> | ErrorResponse;

export type GetSubTaskData = {
    id: string;
};

export type GetSubTaskResponse = Subtask | ErrorResponse;

export type GetSubTasksByTaskTypeData = {
    taskTypeId: string;
};

export type GetSubTasksByTaskTypeResponse = Array<Subtask> | ErrorResponse;

export type CreateScheduleData = {
    requestBody: ScheduleRequest;
};

export type CreateScheduleResponse = Schedule | ErrorResponse;

export type GetSchedulesResponse = Array<Schedule> | ErrorResponse;

export type GetScheduleData = {
    id: string;
};

export type GetScheduleResponse = Schedule | ErrorResponse;

export type UpdateScheduleData = {
    id: string;
    requestBody: ScheduleRequest;
};

export type UpdateScheduleResponse = SuccessResponse | ErrorResponse;

export type DeleteScheduleData = {
    id: string;
};

export type DeleteScheduleResponse = SuccessResponse | ErrorResponse;

export type GetSchedulesForCaregiverData = {
    caregiverId: string;
};

export type GetSchedulesForCaregiverResponse = Array<Schedule> | ErrorResponse;

export type GetSchedulesForRecipientData = {
    recipientId: string;
};

export type GetSchedulesForRecipientResponse = Array<Schedule> | ErrorResponse;

export type GetSchedulesForCaregiverAndRecipientData = {
    caregiverId: string;
    recipientId: string;
};

export type GetSchedulesForCaregiverAndRecipientResponse = Array<Schedule> | ErrorResponse;

export type AddRecipientToCaregiverData = {
    requestBody: RelationshipRequest;
};

export type AddRecipientToCaregiverResponse = RecipientCaregiverRelationship | ErrorResponse;

export type GetAllRelationshipsResponse = Array<RecipientCaregiverRelationship> | ErrorResponse;

export type GetRelationshipsForRecipientData = {
    id: string;
};

export type GetRelationshipsForRecipientResponse = Array<RecipientCaregiverRelationship> | ErrorResponse;

export type GetRelationshipsForCaregiverData = {
    id: string;
};

export type GetRelationshipsForCaregiverResponse = Array<RecipientCaregiverRelationship> | ErrorResponse;

export type UpdateRelationshipData = {
    id: string;
    requestBody: RelationshipRequest;
};

export type UpdateRelationshipResponse = SuccessResponse | ErrorResponse;

export type DeleteRelationshipData = {
    id: string;
};

export type DeleteRelationshipResponse = SuccessResponse | ErrorResponse;

export type GetRecipientsResponse = Array<RecipientWithoutPassword> | ErrorResponse;

export type CreateRecipientData = {
    requestBody: CreateRecipientRequest;
};

export type CreateRecipientResponse = RecipientWithoutPassword | ErrorResponse;

export type GetRecipientData = {
    id: string;
};

export type GetRecipientResponse = RecipientWithoutPassword | ErrorResponse;

export type UpdateRecipientData = {
    id: string;
    requestBody: {
        note?: string;
        fourHandCareNeeded?: boolean;
        address: string;
        phone: string;
        email: string;
        name: string;
    };
};

export type UpdateRecipientResponse = SuccessResponse | ErrorResponse;

export type DeleteRecipientData = {
    id: string;
};

export type DeleteRecipientResponse = SuccessResponse | ErrorResponse;

export type UpdateRecipientPasswordData = {
    id: string;
    requestBody: UpdateRecipientPasswordRequest;
};

export type UpdateRecipientPasswordResponse = SuccessResponse | ErrorResponse;

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse = LoginSuccessResponse | ErrorResponse;

export type CreateLogData = {
    requestBody: LogEntry;
};

export type CreateLogResponse = LogCreateResponse | ErrorResponse;

export type GetLogsResponse = Array<LogEntry> | ErrorResponse;

export type GetLogByIdData = {
    id: string;
};

export type GetLogByIdResponse = LogEntry | ErrorResponse;

export type UpdateLogData = {
    id: string;
    requestBody: UpdateLogEntry;
};

export type UpdateLogResponse = SuccessResponse | ErrorResponse;

export type DeleteLogData = {
    id: string;
};

export type DeleteLogResponse = SuccessResponse | ErrorResponse;

export type GetOpenLogsResponse = Array<LogEntry> | ErrorResponse;

export type GetLogsForRelationshipData = {
    caregiverId: string;
    recipientId: string;
};

export type GetLogsForRelationshipResponse = Array<LogEntry> | ErrorResponse;

export type GetCaregiversResponse = Array<CaregiverWithoutPassword> | ErrorResponse;

export type CreateCaregiverData = {
    requestBody: CreateCaregiverRequest;
};

export type CreateCaregiverResponse = CaregiverWithoutPassword | ErrorResponse;

export type GetCaregiverData = {
    id: string;
};

export type GetCaregiverResponse = CaregiverWithoutPassword | ErrorResponse;

export type UpdateCaregiverData = {
    id: string;
    requestBody: {
        phone: string;
        email: string;
        name: string;
    };
};

export type UpdateCaregiverResponse = SuccessResponse | ErrorResponse;

export type DeleteCaregiverData = {
    id: string;
};

export type DeleteCaregiverResponse = SuccessResponse | ErrorResponse;

export type UpdateCaregiverPasswordData = {
    id: string;
    requestBody: UpdateCaregiverPasswordRequest;
};

export type UpdateCaregiverPasswordResponse = SuccessResponse | ErrorResponse;

export type GetAdminsResponse = Array<AdminWithoutPassword> | ErrorResponse;

export type CreateAdminData = {
    requestBody: CreateAdminRequest;
};

export type CreateAdminResponse = AdminWithoutPassword | ErrorResponse;

export type GetAdminData = {
    id: string;
};

export type GetAdminResponse = AdminWithoutPassword | ErrorResponse;

export type UpdateAdminData = {
    id: string;
    requestBody: {
        email: string;
        name: string;
    };
};

export type UpdateAdminResponse = SuccessResponse | ErrorResponse;

export type DeleteAdminData = {
    id: string;
};

export type DeleteAdminResponse = SuccessResponse | ErrorResponse;

export type UpdateAdminPasswordData = {
    id: string;
    requestBody: UpdateAdminPasswordRequest;
};

export type UpdateAdminPasswordResponse = SuccessResponse | ErrorResponse;
