// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
    PostLoginData,
    PostLoginResponse,
    PostLogsData,
    PostLogsResponse,
    GetLogsResponse,
    GetLogsByIdData,
    GetLogsByIdResponse,
    PutLogsByIdData,
    PutLogsByIdResponse,
    DeleteLogsByIdData,
    DeleteLogsByIdResponse,
    GetLogsOpenResponse,
    GetLogsRelationshipByRecipientIdByCaregiverIdData,
    GetLogsRelationshipByRecipientIdByCaregiverIdResponse,
    GetAdminsResponse,
    PostAdminsData,
    PostAdminsResponse,
    GetAdminsByIdData,
    GetAdminsByIdResponse,
    PutAdminsByIdData,
    PutAdminsByIdResponse,
    DeleteAdminsByIdData,
    DeleteAdminsByIdResponse,
    PutAdminsByIdPasswordData,
    PutAdminsByIdPasswordResponse,
    GetCaregiversResponse,
    PostCaregiversData,
    PostCaregiversResponse,
    GetCaregiversByIdData,
    GetCaregiversByIdResponse,
    PutCaregiversByIdData,
    PutCaregiversByIdResponse,
    DeleteCaregiversByIdData,
    DeleteCaregiversByIdResponse,
    PutCaregiversByIdPasswordData,
    PutCaregiversByIdPasswordResponse,
    GetRecipientsResponse,
    PostRecipientsData,
    PostRecipientsResponse,
    GetRecipientsByIdData,
    GetRecipientsByIdResponse,
    PutRecipientsByIdData,
    PutRecipientsByIdResponse,
    DeleteRecipientsByIdData,
    DeleteRecipientsByIdResponse,
    PutRecipientsByIdPasswordData,
    PutRecipientsByIdPasswordResponse,
    PostRecipientsCaregiversData,
    PostRecipientsCaregiversResponse,
    PostCaregiversRecipientsData,
    PostCaregiversRecipientsResponse,
    GetRecipientsByIdCaregiversData,
    GetRecipientsByIdCaregiversResponse,
    GetCaregiversByIdRecipientsData,
    GetCaregiversByIdRecipientsResponse,
    PostSchedulesData,
    PostSchedulesResponse,
    GetSchedulesResponse,
    GetSchedulesByIdData,
    GetSchedulesByIdResponse,
    PutSchedulesByIdData,
    PutSchedulesByIdResponse,
    DeleteSchedulesByIdData,
    DeleteSchedulesByIdResponse,
    GetSchedulesCaregiverByCaregiverIdData,
    GetSchedulesCaregiverByCaregiverIdResponse,
    GetSchedulesRecipientByRecipientIdData,
    GetSchedulesRecipientByRecipientIdResponse,
    GetSchedulesByIdRecipientData,
    GetSchedulesByIdRecipientResponse,
    GetSchedulesByCaregiverIdByRecipientIdData,
    GetSchedulesByCaregiverIdByRecipientIdResponse,
    PostTasktypesData,
    PostTasktypesResponse,
    GetTasktypesResponse,
    GetTasktypesByIdData,
    GetTasktypesByIdResponse,
    PostSubtasksData,
    PostSubtasksResponse,
    GetSubtasksResponse,
    GetSubtasksByIdData,
    GetSubtasksByIdResponse,
    GetSubtasksTasktypeByTaskTypeIdData,
    GetSubtasksTasktypeByTaskTypeIdResponse,
    GetSchedulesRecipientByRecipientIdLastData,
    GetSchedulesRecipientByRecipientIdLastResponse,
    GetSchedulesRecipientByRecipientIdNextData,
    GetSchedulesRecipientByRecipientIdNextResponse,
    GetSchedulesCaregiverByCaregiverIdTodayData,
    GetSchedulesCaregiverByCaregiverIdTodayResponse,
} from "./types.gen";

/**
 * User login
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful login, returns JWT and user data
 * @throws ApiError
 */
export const postLogin = (data: PostLoginData): CancelablePromise<PostLoginResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/login",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            401: "Invalid password",
            404: "User not found",
            500: "Server error",
        },
    });
};

/**
 * Create a new log entry
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Log created successfully
 * @throws ApiError
 */
export const postLogs = (data: PostLogsData): CancelablePromise<PostLogsResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/logs",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            500: "Error creating log",
        },
    });
};

/**
 * Get all logs
 * @returns unknown List of logs
 * @throws ApiError
 */
export const getLogs = (): CancelablePromise<GetLogsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs",
        errors: {
            500: "Error fetching logs",
        },
    });
};

/**
 * Get a specific log by ID
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Log found
 * @throws ApiError
 */
export const getLogsById = (data: GetLogsByIdData): CancelablePromise<GetLogsByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Log not found",
            500: "Error fetching log",
        },
    });
};

/**
 * Update a log entry by ID
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Log updated
 * @throws ApiError
 */
export const putLogsById = (data: PutLogsByIdData): CancelablePromise<PutLogsByIdResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/logs/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            404: "Log not found",
            500: "Error updating log",
        },
    });
};

/**
 * Delete a log by ID
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Log deleted
 * @throws ApiError
 */
export const deleteLogsById = (data: DeleteLogsByIdData): CancelablePromise<DeleteLogsByIdResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/logs/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Log not found",
            500: "Error deleting log",
        },
    });
};

/**
 * Get all logs that are not closed
 * @returns unknown List of open logs
 * @throws ApiError
 */
export const getLogsOpen = (): CancelablePromise<GetLogsOpenResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs/open",
        errors: {
            500: "Error fetching open logs",
        },
    });
};

/**
 * Get logs for a specific recipient-caregiver relationship
 * @param data The data for the request.
 * @param data.recipientId ID of the recipient
 * @param data.caregiverId ID of the caregiver
 * @returns unknown List of logs for the recipient-caregiver relationship
 * @throws ApiError
 */
export const getLogsRelationshipByRecipientIdByCaregiverId = (
    data: GetLogsRelationshipByRecipientIdByCaregiverIdData,
): CancelablePromise<GetLogsRelationshipByRecipientIdByCaregiverIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/logs/relationship/{recipientId}/{caregiverId}",
        path: {
            recipientId: data.recipientId,
            caregiverId: data.caregiverId,
        },
        errors: {
            404: "Relationship not found",
            500: "Server error",
        },
    });
};

/**
 * Get all admins
 * @returns unknown A list of admins
 * @throws ApiError
 */
export const getAdmins = (): CancelablePromise<GetAdminsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/admins",
        errors: {
            401: "Invalid or no token",
            403: "Not authorized",
        },
    });
};

/**
 * Create a new admin
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Admin created successfully
 * @throws ApiError
 */
export const postAdmins = (data: PostAdminsData): CancelablePromise<PostAdminsResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/admins",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            401: "Invalid or no token",
            403: "Not authorized",
            500: "Server error",
        },
    });
};

/**
 * Get an admin by ID
 * @param data The data for the request.
 * @param data.id Admin ID
 * @returns unknown Admin data
 * @throws ApiError
 */
export const getAdminsById = (data: GetAdminsByIdData): CancelablePromise<GetAdminsByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/admins/{id}",
        path: {
            id: data.id,
        },
        errors: {
            401: "Invalid or no token",
            403: "Not authorized",
            404: "Admin not found",
            500: "Server error",
        },
    });
};

/**
 * Update an admin's info
 * @param data The data for the request.
 * @param data.id Admin ID
 * @param data.requestBody
 * @returns unknown Admin updated
 * @throws ApiError
 */
export const putAdminsById = (data: PutAdminsByIdData): CancelablePromise<PutAdminsByIdResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/admins/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            401: "Invalid or no token",
            403: "Not authorized",
            404: "Admin not found",
            500: "Server error",
        },
    });
};

/**
 * Delete an admin
 * @param data The data for the request.
 * @param data.id Admin ID
 * @returns unknown Admin deleted
 * @throws ApiError
 */
export const deleteAdminsById = (data: DeleteAdminsByIdData): CancelablePromise<DeleteAdminsByIdResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/admins/{id}",
        path: {
            id: data.id,
        },
        errors: {
            401: "Invalid or no token",
            403: "Not authorized",
            404: "Admin not found",
            500: "Server error",
        },
    });
};

/**
 * Update an admins's password
 * @param data The data for the request.
 * @param data.id Admin ID
 * @param data.requestBody
 * @returns unknown Password updated
 * @throws ApiError
 */
export const putAdminsByIdPassword = (
    data: PutAdminsByIdPasswordData,
): CancelablePromise<PutAdminsByIdPasswordResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/admins/{id}/password",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Invalid current password or missing field",
            401: "Invalid or no token",
            403: "Not authorized",
            404: "Admin not found",
            500: "Server error",
        },
    });
};

/**
 * Get all caregivers
 * @returns unknown A list of caregivers
 * @throws ApiError
 */
export const getCaregivers = (): CancelablePromise<GetCaregiversResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/caregivers",
    });
};

/**
 * Create a new caregiver
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Caregiver created successfully
 * @throws ApiError
 */
export const postCaregivers = (data: PostCaregiversData): CancelablePromise<PostCaregiversResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/caregivers",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            500: "Server error",
        },
    });
};

/**
 * Get a caregiver by ID
 * @param data The data for the request.
 * @param data.id Caregiver ID
 * @returns unknown Caregiver data
 * @throws ApiError
 */
export const getCaregiversById = (data: GetCaregiversByIdData): CancelablePromise<GetCaregiversByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/caregivers/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Caregiver not found",
            500: "Server error",
        },
    });
};

/**
 * Update a caregiver's info
 * @param data The data for the request.
 * @param data.id Caregiver ID
 * @param data.requestBody
 * @returns unknown Caregiver updated
 * @throws ApiError
 */
export const putCaregiversById = (data: PutCaregiversByIdData): CancelablePromise<PutCaregiversByIdResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/caregivers/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            404: "Caregiver not found",
            500: "Server error",
        },
    });
};

/**
 * Delete a caregiver
 * @param data The data for the request.
 * @param data.id Caregiver ID
 * @returns unknown Caregiver deleted
 * @throws ApiError
 */
export const deleteCaregiversById = (
    data: DeleteCaregiversByIdData,
): CancelablePromise<DeleteCaregiversByIdResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/caregivers/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Caregiver not found",
            500: "Server error",
        },
    });
};

/**
 * Update a caregiver's password
 * @param data The data for the request.
 * @param data.id Caregiver ID
 * @param data.requestBody
 * @returns unknown Password updated
 * @throws ApiError
 */
export const putCaregiversByIdPassword = (
    data: PutCaregiversByIdPasswordData,
): CancelablePromise<PutCaregiversByIdPasswordResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/caregivers/{id}/password",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Invalid current password or missing field",
            404: "Caregiver not found",
            500: "Server error",
        },
    });
};

/**
 * Get all recipients
 * @returns unknown A list of recipients
 * @throws ApiError
 */
export const getRecipients = (): CancelablePromise<GetRecipientsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/recipients",
    });
};

/**
 * Create a new recipient
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Recipient created successfully
 * @throws ApiError
 */
export const postRecipients = (data: PostRecipientsData): CancelablePromise<PostRecipientsResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/recipients",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            500: "Server error",
        },
    });
};

/**
 * Get a recipient by ID
 * @param data The data for the request.
 * @param data.id Recipient ID
 * @returns unknown Recipient data
 * @throws ApiError
 */
export const getRecipientsById = (data: GetRecipientsByIdData): CancelablePromise<GetRecipientsByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/recipients/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Recipient not found",
            500: "Server error",
        },
    });
};

/**
 * Update a recipient's info
 * @param data The data for the request.
 * @param data.id Recipient ID
 * @param data.requestBody
 * @returns unknown Recipient updated
 * @throws ApiError
 */
export const putRecipientsById = (data: PutRecipientsByIdData): CancelablePromise<PutRecipientsByIdResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/recipients/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            404: "Recipient not found",
            500: "Server error",
        },
    });
};

/**
 * Delete a recipient
 * @param data The data for the request.
 * @param data.id Recipient ID
 * @returns unknown Recipient deleted
 * @throws ApiError
 */
export const deleteRecipientsById = (
    data: DeleteRecipientsByIdData,
): CancelablePromise<DeleteRecipientsByIdResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/recipients/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Recipient not found",
            500: "Server error",
        },
    });
};

/**
 * Update a recipient's password
 * @param data The data for the request.
 * @param data.id Recipient ID
 * @param data.requestBody
 * @returns unknown Password updated
 * @throws ApiError
 */
export const putRecipientsByIdPassword = (
    data: PutRecipientsByIdPasswordData,
): CancelablePromise<PutRecipientsByIdPasswordResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/recipients/{id}/password",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Invalid current password or missing field",
            404: "Recipient not found",
            500: "Server error",
        },
    });
};

/**
 * Assign a caregiver to a recipient
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Caregiver assigned to recipient
 * @throws ApiError
 */
export const postRecipientsCaregivers = (
    data: PostRecipientsCaregiversData,
): CancelablePromise<PostRecipientsCaregiversResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/recipients/caregivers",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Assign a recipient to a caregiver
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Recipient assigned to caregiver
 * @throws ApiError
 */
export const postCaregiversRecipients = (
    data: PostCaregiversRecipientsData,
): CancelablePromise<PostCaregiversRecipientsResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/caregivers/recipients",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Get all caregivers assigned to a recipient
 * @param data The data for the request.
 * @param data.id Recipient ID
 * @returns unknown A list of caregivers
 * @throws ApiError
 */
export const getRecipientsByIdCaregivers = (
    data: GetRecipientsByIdCaregiversData,
): CancelablePromise<GetRecipientsByIdCaregiversResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/recipients/{id}/caregivers",
        path: {
            id: data.id,
        },
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Get all recipients assigned to a caregiver
 * @param data The data for the request.
 * @param data.id Caregiver ID
 * @returns unknown A list of recipients
 * @throws ApiError
 */
export const getCaregiversByIdRecipients = (
    data: GetCaregiversByIdRecipientsData,
): CancelablePromise<GetCaregiversByIdRecipientsResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/caregivers/{id}/recipients",
        path: {
            id: data.id,
        },
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Create a new schedule
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Schedule created
 * @throws ApiError
 */
export const postSchedules = (data: PostSchedulesData): CancelablePromise<PostSchedulesResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/schedules",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required fields",
            500: "Server error",
        },
    });
};

/**
 * Get all schedules
 * @returns string List of all schedules
 * @throws ApiError
 */
export const getSchedules = (): CancelablePromise<GetSchedulesResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules",
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Get schedule by ID
 * @param data The data for the request.
 * @param data.id Schedule ID
 * @returns unknown Schedule details
 * @throws ApiError
 */
export const getSchedulesById = (data: GetSchedulesByIdData): CancelablePromise<GetSchedulesByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Schedule not found",
            500: "Server error",
        },
    });
};

/**
 * Update a schedule by ID
 * @param data The data for the request.
 * @param data.id Schedule ID
 * @param data.requestBody
 * @returns unknown Schedule updated
 * @throws ApiError
 */
export const putSchedulesById = (data: PutSchedulesByIdData): CancelablePromise<PutSchedulesByIdResponse> => {
    return __request(OpenAPI, {
        method: "PUT",
        url: "/schedules/{id}",
        path: {
            id: data.id,
        },
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required fields",
            404: "Schedule not found",
            500: "Server error",
        },
    });
};

/**
 * Delete a schedule by ID
 * @param data The data for the request.
 * @param data.id Schedule ID
 * @returns unknown Schedule deleted
 * @throws ApiError
 */
export const deleteSchedulesById = (data: DeleteSchedulesByIdData): CancelablePromise<DeleteSchedulesByIdResponse> => {
    return __request(OpenAPI, {
        method: "DELETE",
        url: "/schedules/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Schedule not found",
            500: "Server error",
        },
    });
};

/**
 * Get all schedules for a specific caregiver
 * @param data The data for the request.
 * @param data.caregiverId ID of the caregiver
 * @returns unknown List of schedules for the caregiver
 * @throws ApiError
 */
export const getSchedulesCaregiverByCaregiverId = (
    data: GetSchedulesCaregiverByCaregiverIdData,
): CancelablePromise<GetSchedulesCaregiverByCaregiverIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/caregiver/{caregiverId}",
        path: {
            caregiverId: data.caregiverId,
        },
        errors: {
            404: "No schedules found for this caregiver",
            500: "Server error",
        },
    });
};

/**
 * Get all schedules for a specific recipient
 * @param data The data for the request.
 * @param data.recipientId ID of the recipient
 * @returns unknown List of schedules for the recipient
 * @throws ApiError
 */
export const getSchedulesRecipientByRecipientId = (
    data: GetSchedulesRecipientByRecipientIdData,
): CancelablePromise<GetSchedulesRecipientByRecipientIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/recipient/{recipientId}",
        path: {
            recipientId: data.recipientId,
        },
        errors: {
            404: "No schedules found for this recipient",
            500: "Server error",
        },
    });
};

/**
 * Get recipient details for a given schedule
 * @param data The data for the request.
 * @param data.id Schedule ID
 * @returns unknown Recipient details for the schedule
 * @throws ApiError
 */
export const getSchedulesByIdRecipient = (
    data: GetSchedulesByIdRecipientData,
): CancelablePromise<GetSchedulesByIdRecipientResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/{id}/recipient",
        path: {
            id: data.id,
        },
        errors: {
            404: "Recipient not found for this schedule",
            500: "Server error",
        },
    });
};

/**
 * Get all schedules between a caregiver and a recipient
 * @param data The data for the request.
 * @param data.caregiverId ID of the caregiver
 * @param data.recipientId ID of the recipient
 * @returns unknown List of schedules between the caregiver and recipient
 * @throws ApiError
 */
export const getSchedulesByCaregiverIdByRecipientId = (
    data: GetSchedulesByCaregiverIdByRecipientIdData,
): CancelablePromise<GetSchedulesByCaregiverIdByRecipientIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/{caregiverId}/{recipientId}",
        path: {
            caregiverId: data.caregiverId,
            recipientId: data.recipientId,
        },
        errors: {
            404: "No schedules found for this caregiver-recipient pair",
            500: "Server error",
        },
    });
};

/**
 * Create a new task type
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Task type created
 * @throws ApiError
 */
export const postTasktypes = (data: PostTasktypesData): CancelablePromise<PostTasktypesResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/tasktypes",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required field",
            500: "Server error",
        },
    });
};

/**
 * Get all task types
 * @returns unknown List of task types
 * @throws ApiError
 */
export const getTasktypes = (): CancelablePromise<GetTasktypesResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/tasktypes",
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Get a specific task type by ID
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Task type details
 * @throws ApiError
 */
export const getTasktypesById = (data: GetTasktypesByIdData): CancelablePromise<GetTasktypesByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/tasktypes/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Task type not found",
            500: "Server error",
        },
    });
};

/**
 * Create a new subtask
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Subtask created
 * @throws ApiError
 */
export const postSubtasks = (data: PostSubtasksData): CancelablePromise<PostSubtasksResponse> => {
    return __request(OpenAPI, {
        method: "POST",
        url: "/subtasks",
        body: data.requestBody,
        mediaType: "application/json",
        errors: {
            400: "Missing required fields",
            500: "Server error",
        },
    });
};

/**
 * Get all subtasks
 * @returns unknown List of all subtasks
 * @throws ApiError
 */
export const getSubtasks = (): CancelablePromise<GetSubtasksResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/subtasks",
        errors: {
            500: "Server error",
        },
    });
};

/**
 * Get a specific subtask by ID
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Subtask details
 * @throws ApiError
 */
export const getSubtasksById = (data: GetSubtasksByIdData): CancelablePromise<GetSubtasksByIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/subtasks/{id}",
        path: {
            id: data.id,
        },
        errors: {
            404: "Subtask not found",
            500: "Server error",
        },
    });
};

/**
 * Get all subtasks by task type ID
 * @param data The data for the request.
 * @param data.taskTypeId
 * @returns unknown List of subtasks for the given task type
 * @throws ApiError
 */
export const getSubtasksTasktypeByTaskTypeId = (
    data: GetSubtasksTasktypeByTaskTypeIdData,
): CancelablePromise<GetSubtasksTasktypeByTaskTypeIdResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/subtasks/tasktype/{taskTypeId}",
        path: {
            taskTypeId: data.taskTypeId,
        },
        errors: {
            404: "No subtasks found",
            500: "Server error",
        },
    });
};

/**
 * Get the most recent past schedule for a recipient
 * @param data The data for the request.
 * @param data.recipientId
 * @returns unknown Last past schedule
 * @throws ApiError
 */
export const getSchedulesRecipientByRecipientIdLast = (
    data: GetSchedulesRecipientByRecipientIdLastData,
): CancelablePromise<GetSchedulesRecipientByRecipientIdLastResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/recipient/{recipientId}/last",
        path: {
            recipientId: data.recipientId,
        },
        errors: {
            404: "No past schedule found",
            500: "Server error",
        },
    });
};

/**
 * Get the next upcoming schedule for a recipient
 * @param data The data for the request.
 * @param data.recipientId
 * @returns unknown Next upcoming schedule
 * @throws ApiError
 */
export const getSchedulesRecipientByRecipientIdNext = (
    data: GetSchedulesRecipientByRecipientIdNextData,
): CancelablePromise<GetSchedulesRecipientByRecipientIdNextResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/recipient/{recipientId}/next",
        path: {
            recipientId: data.recipientId,
        },
        errors: {
            404: "No upcoming schedule found",
            500: "Server error",
        },
    });
};

/**
 * Get today's schedules for a caregiver
 * @param data The data for the request.
 * @param data.caregiverId
 * @returns unknown List of today's schedules
 * @throws ApiError
 */
export const getSchedulesCaregiverByCaregiverIdToday = (
    data: GetSchedulesCaregiverByCaregiverIdTodayData,
): CancelablePromise<GetSchedulesCaregiverByCaregiverIdTodayResponse> => {
    return __request(OpenAPI, {
        method: "GET",
        url: "/schedules/caregiver/{caregiverId}/today",
        path: {
            caregiverId: data.caregiverId,
        },
        errors: {
            500: "Server error",
        },
    });
};
