// This file is auto-generated by @hey-api/openapi-ts

export type PostLoginData = {
    requestBody: {
        email: string;
        password: string;
    };
};

export type PostLoginResponse = {
    message?: string;
    role?: string;
    token?: string;
    user?: {
        id?: number;
        name?: string;
        email?: string;
    };
};

export type PostLogsData = {
    requestBody: {
        id: string;
        date: string;
        relationshipId: string;
        finished: boolean;
        closed: boolean;
        tasks: Array<{
            subTaskId: string;
            startTime: string;
            endTime: string;
            done: boolean;
            note?: string;
        }>;
    };
};

export type PostLogsResponse = unknown;

export type GetLogsResponse = Array<{
    _id?: string;
    _index?: string;
    _source?: {
        id?: string;
        date?: string;
        relationshipId?: string;
        finished?: boolean;
        closed?: boolean;
        tasks?: Array<{
            subTaskId?: string;
            startTime?: string;
            endTime?: string;
            done?: boolean;
            note?: string;
        }>;
    };
}>;

export type GetLogsByIdData = {
    id: string;
};

export type GetLogsByIdResponse = {
    _id?: string;
    _index?: string;
    _source?: {
        id?: string;
        date?: string;
        relationshipId?: string;
        finished?: boolean;
        closed?: boolean;
        tasks?: Array<{
            subTaskId?: string;
            startTime?: string;
            endTime?: string;
            done?: boolean;
            note?: string;
        }>;
    };
};

export type PutLogsByIdData = {
    id: string;
    requestBody: {
        _id?: string;
        _index?: string;
        _source?: {
            id?: string;
            date?: string;
            relationshipId?: string;
            finished?: boolean;
            closed?: boolean;
            tasks?: Array<{
                subTaskId?: string;
                startTime?: string;
                endTime?: string;
                done?: boolean;
                note?: string;
            }>;
        };
    };
};

export type PutLogsByIdResponse = unknown;

export type DeleteLogsByIdData = {
    id: string;
};

export type DeleteLogsByIdResponse = unknown;

export type GetLogsOpenResponse = Array<{
    _id?: string;
    _index?: string;
    _source?: {
        id?: string;
        date?: string;
        relationshipId?: string;
        finished?: boolean;
        closed?: boolean;
        tasks?: Array<{
            subTaskId?: string;
            startTime?: string;
            endTime?: string;
            done?: boolean;
            note?: string;
        }>;
    };
}>;

export type GetLogsRelationshipByRecipientIdByCaregiverIdData = {
    /**
     * ID of the caregiver
     */
    caregiverId: string;
    /**
     * ID of the recipient
     */
    recipientId: string;
};

export type GetLogsRelationshipByRecipientIdByCaregiverIdResponse = Array<{
    id?: string;
    date?: string;
    relationshipId?: string;
    finished?: boolean;
    closed?: boolean;
    tasks?: Array<{
        subTaskId?: string;
        startTime?: string;
        endTime?: string;
        done?: boolean;
        note?: string;
    }>;
}>;

export type GetAdminsResponse = Array<{
    id?: number;
    name?: string;
    email?: string;
}>;

export type PostAdminsData = {
    requestBody: {
        name: string;
        email: string;
        password: string;
    };
};

export type PostAdminsResponse = unknown;

export type GetAdminsByIdData = {
    /**
     * Admin ID
     */
    id: number;
};

export type GetAdminsByIdResponse = unknown;

export type PutAdminsByIdData = {
    /**
     * Admin ID
     */
    id: number;
    requestBody: {
        name: string;
        email: string;
    };
};

export type PutAdminsByIdResponse = unknown;

export type DeleteAdminsByIdData = {
    /**
     * Admin ID
     */
    id: number;
};

export type DeleteAdminsByIdResponse = unknown;

export type PutAdminsByIdPasswordData = {
    /**
     * Admin ID
     */
    id: number;
    requestBody: {
        currentPassword: string;
        newPassword: string;
    };
};

export type PutAdminsByIdPasswordResponse = unknown;

export type GetCaregiversResponse = Array<{
    id?: number;
    name?: string;
    phone?: string;
    email?: string;
}>;

export type PostCaregiversData = {
    requestBody: {
        name: string;
        email: string;
        phone: string;
        password: string;
    };
};

export type PostCaregiversResponse = unknown;

export type GetCaregiversByIdData = {
    /**
     * Caregiver ID
     */
    id: number;
};

export type GetCaregiversByIdResponse = unknown;

export type PutCaregiversByIdData = {
    /**
     * Caregiver ID
     */
    id: number;
    requestBody: {
        name: string;
        email: string;
        phone: string;
    };
};

export type PutCaregiversByIdResponse = unknown;

export type DeleteCaregiversByIdData = {
    /**
     * Caregiver ID
     */
    id: number;
};

export type DeleteCaregiversByIdResponse = unknown;

export type PutCaregiversByIdPasswordData = {
    /**
     * Caregiver ID
     */
    id: number;
    requestBody: {
        currentPassword: string;
        newPassword: string;
    };
};

export type PutCaregiversByIdPasswordResponse = unknown;

export type GetRecipientsResponse = Array<{
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    four_hand_care_needed?: boolean;
    caregiver_note?: string;
}>;

export type PostRecipientsData = {
    requestBody: {
        name: string;
        email: string;
        phone: string;
        address: string;
        four_hand_care_needed?: boolean;
        caregiver_note?: string;
        password: string;
    };
};

export type PostRecipientsResponse = unknown;

export type GetRecipientsByIdData = {
    /**
     * Recipient ID
     */
    id: number;
};

export type GetRecipientsByIdResponse = unknown;

export type PutRecipientsByIdData = {
    /**
     * Recipient ID
     */
    id: number;
    requestBody: {
        name: string;
        email: string;
        phone: string;
        address: string;
        four_hand_care_needed?: boolean;
        caregiver_note?: string;
    };
};

export type PutRecipientsByIdResponse = unknown;

export type DeleteRecipientsByIdData = {
    /**
     * Recipient ID
     */
    id: number;
};

export type DeleteRecipientsByIdResponse = unknown;

export type PutRecipientsByIdPasswordData = {
    /**
     * Recipient ID
     */
    id: number;
    requestBody: {
        currentPassword: string;
        newPassword: string;
    };
};

export type PutRecipientsByIdPasswordResponse = unknown;

export type PostRecipientsCaregiversData = {
    requestBody: {
        recipientId: number;
        caregiverId: number;
    };
};

export type PostRecipientsCaregiversResponse = unknown;

export type PostCaregiversRecipientsData = {
    requestBody: {
        recipientId: number;
        caregiverId: number;
    };
};

export type PostCaregiversRecipientsResponse = unknown;

export type GetRecipientsByIdCaregiversData = {
    /**
     * Recipient ID
     */
    id: number;
};

export type GetRecipientsByIdCaregiversResponse = Array<{
    id?: number;
    name?: string;
    phone?: string;
    email?: string;
}>;

export type GetCaregiversByIdRecipientsData = {
    /**
     * Caregiver ID
     */
    id: number;
};

export type GetCaregiversByIdRecipientsResponse = Array<{
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
}>;

export type DeleteRelationshipsByIdData = {
    /**
     * Relationship ID
     */
    id: number;
};

export type DeleteRelationshipsByIdResponse = unknown;

export type PutRelationshipsByIdData = {
    /**
     * Relationship ID
     */
    id: number;
    requestBody: {
        recipientId: number;
        caregiverId: number;
    };
};

export type PutRelationshipsByIdResponse = unknown;

export type GetRelationshipsResponse = Array<{
    relationship_id?: number;
    recipient_id?: number;
    recipient_name?: string;
    recipient_email?: string;
    caregiver_id?: number;
    caregiver_name?: string;
    caregiver_email?: string;
}>;

export type PostSchedulesData = {
    requestBody: {
        relationship_id: number;
        date: string;
        start_time: string;
        end_time: string;
    };
};

export type PostSchedulesResponse = unknown;

export type GetSchedulesResponse = Array<{
    relationship_id?: number;
    date?: string;
    start_time?: string;
    end_time?: string;
}>;

export type GetSchedulesByIdData = {
    /**
     * Schedule ID
     */
    id: number;
};

export type GetSchedulesByIdResponse = unknown;

export type PutSchedulesByIdData = {
    /**
     * Schedule ID
     */
    id: number;
    requestBody: {
        relationship_id: number;
        date: string;
        start_time: string;
        end_time: string;
    };
};

export type PutSchedulesByIdResponse = unknown;

export type DeleteSchedulesByIdData = {
    /**
     * Schedule ID
     */
    id: number;
};

export type DeleteSchedulesByIdResponse = unknown;

export type GetSchedulesCaregiverByCaregiverIdData = {
    /**
     * ID of the caregiver
     */
    caregiverId: number;
};

export type GetSchedulesCaregiverByCaregiverIdResponse = unknown;

export type GetSchedulesRecipientByRecipientIdData = {
    /**
     * ID of the recipient
     */
    recipientId: number;
};

export type GetSchedulesRecipientByRecipientIdResponse = unknown;

export type GetSchedulesByIdRecipientData = {
    /**
     * Schedule ID
     */
    id: number;
};

export type GetSchedulesByIdRecipientResponse = unknown;

export type GetSchedulesByCaregiverIdByRecipientIdData = {
    /**
     * ID of the caregiver
     */
    caregiverId: number;
    /**
     * ID of the recipient
     */
    recipientId: number;
};

export type GetSchedulesByCaregiverIdByRecipientIdResponse = unknown;

export type PostTasktypesData = {
    requestBody: {
        type: string;
    };
};

export type PostTasktypesResponse = unknown;

export type GetTasktypesResponse = unknown;

export type GetTasktypesByIdData = {
    id: number;
};

export type GetTasktypesByIdResponse = unknown;

export type PostSubtasksData = {
    requestBody: {
        title: string;
        taskTypeId: number;
    };
};

export type PostSubtasksResponse = unknown;

export type GetSubtasksResponse = unknown;

export type GetSubtasksByIdData = {
    id: number;
};

export type GetSubtasksByIdResponse = unknown;

export type GetSubtasksTasktypeByTaskTypeIdData = {
    taskTypeId: number;
};

export type GetSubtasksTasktypeByTaskTypeIdResponse = unknown;

export type GetSchedulesRecipientByRecipientIdLastData = {
    recipientId: number;
};

export type GetSchedulesRecipientByRecipientIdLastResponse = unknown;

export type GetSchedulesRecipientByRecipientIdNextData = {
    recipientId: number;
};

export type GetSchedulesRecipientByRecipientIdNextResponse = unknown;

export type GetSchedulesCaregiverByCaregiverIdTodayData = {
    caregiverId: number;
};

export type GetSchedulesCaregiverByCaregiverIdTodayResponse = unknown;
